const BRL=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
let DATA=null;let CURRENT='home';
const $=id=>document.getElementById(id);
const money=v=>BRL.format(Number(v||0));
const cls=s=>{s=String(s||'').toLowerCase();if(s.includes('não')||s.includes('nao'))return'nao';if(s.includes('cobrar'))return'cobrar';return'pago'};
async function loadData(){const r=await fetch('data/clientes.json?v=52');DATA=await r.json();renderAll();}
function showToast(t='Copiado'){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function copyText(t){navigator.clipboard?.writeText(t);showToast()}
function msg(c,t='cobranca'){if(t==='visita')return `Olá, ${c.nome}! Tudo bem? Sua carteira Collin está próxima de finalizar. Posso te enviar opções para reposição e manter seus produtos girando?`;return `Olá, ${c.nome}! Tudo bem? Passando para lembrar sobre o saldo em aberto da Collin Professional.\n\nCliente: ${c.nome}\nSaldo: ${money(c.saldoDevedor)}\nStatus: ${c.status}\n\nConsegue me dar um retorno hoje?`}
function whats(c,t){return 'https://wa.me/?text='+encodeURIComponent(msg(c,t))}
function maps(c){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(c.bairro+' Santa Catarina')}
function actions(c,t){return `<div class="actions"><a class="btn whatsapp" target="_blank" href="${whats(c,t)}">Whats</a><button class="btn dark" onclick="copyText(msg(DATA.clientes.find(x=>x.id===${c.id}),'${t||'cobranca'}'))">Copiar</button><a class="btn blue" target="_blank" href="${maps(c)}">Mapa</a></div>`}
function tab(id){CURRENT=id;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$('pageTitle').textContent={home:'Dashboard Executivo',clientes:'Clientes',bairros:'Bairros',cobranca:'Cobrança',visitas:'Visitas',metas:'Metas',comissao:'Comissão',performance:'Performance',relatorio:'Relatório'}[id];setTimeout(drawAll,50)}
function renderKpis(){const k=DATA.kpis,g=DATA.goals;const cards=[['Clientes',k.clientes,'Todos cadastrados'],['Ativos',k.ativos,'Pago + Não pago + Cobrar'],['Inativos',k.inativos,'Quitados'],['Recebido semana',money(k.recebidoSemana),'Parcelas pagas'],['Carteira',money(k.carteira),'Total carteira'],['Devedor',money(k.devedor),'Saldo aberto'],['Comissão semana',money(k.comissaoSemana),'15% + ajuda custo'],['Visitas',k.visitasCarteiraBaixa,'Carteira < R$150']];$('homeKpis').innerHTML=cards.map(c=>`<article class="kpi"><small>${c[0]}</small><b>${c[1]}</b><span>${c[2]}</span></article>`).join('');$('heroGoal').textContent=`${g.clientesAbertos}/${g.clientesMeta}`;$('heroProgress').style.width=g.clientesProgresso+'%'}
function renderSmart(){const k=DATA.kpis;const cards=[['Maior devedor',`${k.maiorDevedor?.nome||'-'} — ${money(k.maiorDevedor?.saldoDevedor)}`],['Maior parcela',`${k.maiorParcela?.nome||'-'} — ${money(k.maiorParcela?.valorParcela)}`],['Ticket médio',money(k.ticketMedio)],['Projeção salário mês',money(k.projecaoSalarioMes)]];$('smartCards').innerHTML=cards.map(c=>`<article class="card"><small>${c[0]}</small><b>${c[1]}</b></article>`).join('')}
function renderClientes(){const q=($('searchInput').value||'').toLowerCase();const list=DATA.clientes.filter(c=>(c.cliente+' '+c.bairro+' '+c.status).toLowerCase().includes(q));$('clientRows').innerHTML=list.map(c=>`<tr><td><b>${c.nome}</b><br><small>${c.cliente}</small></td><td>${c.bairro}</td><td>${money(c.saldoCarteira)}</td><td>${money(c.saldoDevedor)}</td><td>${money(c.valorParcela)}</td><td><span class="status ${cls(c.status)}">${c.status}</span></td><td>${actions(c)}</td></tr>`).join('')}
function renderBairros(){$('bairroCards').innerHTML=DATA.bairros.slice(0,15).map((b,i)=>`<article class="card"><small>#${i+1} ${b.bairro}</small><b>${money(b.vendas)}</b><span>${b.clientes} clientes • Devedor ${money(b.devedor)}</span></article>`).join('')}
function renderCobranca(){$('cobrancaCards').innerHTML=DATA.cobrancaPrioridade.map(c=>`<article class="client-card"><h4>${c.nome}</h4><p>${c.bairro} • ${c.status}</p><div class="amount">${money(c.saldoDevedor)}</div><span class="priority ${c.prioridade==='Alta'?'high':c.prioridade==='Média'?'medium':'low'}">${c.prioridade} prioridade</span><div style="margin-top:12px">${actions(c)}</div></article>`).join('')}
function renderVisitas(){$('visitaCards').innerHTML=DATA.visitas.map(c=>`<article class="client-card"><h4>${c.nome}</h4><p>${c.bairro} • ${c.status}</p><div class="amount">${money(c.saldoCarteira)}</div><span class="priority medium">Carteira menor que R$150</span><div style="margin-top:12px">${actions(c,'visita')}</div></article>`).join('')}
function renderMetas(){const k=DATA.kpis,g=DATA.goals;const sem=(k.recebidoSemana/g.recebimentoMetaSemanal*100).toFixed(1);const mes=(k.recebidoSemana/g.recebimentoMetaMensal*100).toFixed(1);const sal=(k.comissao5Semanas/g.salarioMetaMensal*100).toFixed(1);const cards=[['Clientes abertos',`${g.clientesAbertos}/${g.clientesMeta}`,`${g.clientesProgresso}%`],['Meta semanal',`${money(k.recebidoSemana)} / ${money(g.recebimentoMetaSemanal)}`,`${sem}%`],['Meta mensal',`${money(k.recebidoSemana)} / ${money(g.recebimentoMetaMensal)}`,`${mes}%`],['Meta salário',`${money(k.comissao5Semanas)} / ${money(g.salarioMetaMensal)}`,`${sal}%`]];$('metaCards').innerHTML=cards.map(c=>`<article class="kpi"><small>${c[0]}</small><b>${c[1]}</b><span>${c[2]}</span></article>`).join('')}
function renderComissao(){const k=DATA.kpis,g=DATA.goals;const cards=[['Comissão semana',money(k.comissaoSemana),'15% das parcelas + R$375'],['Ajuda custo',money(g.ajudaCusto),'Fixo semanal'],['Total 4 semanas',money(k.comissao4Semanas),'Histórico'],['Total + semana 5',money(k.comissao5Semanas),'Atual'],['Média semanal',money(k.mediaComissaoSemanal),'Média'],['Projeção mês',money(k.projecaoSalarioMes),'Média × 4'],['Meta salário',money(g.salarioMetaMensal),'Objetivo'],['Faltante',money(Math.max(g.salarioMetaMensal-k.comissao5Semanas,0)),'Para meta']];$('comissaoKpis').innerHTML=cards.map(c=>`<article class="kpi"><small>${c[0]}</small><b>${c[1]}</b><span>${c[2]}</span></article>`).join('')}
function renderPerformance(){const k=DATA.kpis,g=DATA.goals;const cards=[['Evolução semanal','5 semanas','Comissão consolidada'],['Projeção salário',money(k.projecaoSalarioMes),'Média semanal × 4'],['Projeção recebimento',money(k.recebidoSemana*4),'Semana atual × 4'],['Projeção clientes','24/mês','6 clientes × 4 semanas']];$('performanceKpis').innerHTML=cards.map(c=>`<article class="kpi"><small>${c[0]}</small><b>${c[1]}</b><span>${c[2]}</span></article>`).join('')}
function renderReport(){const k=DATA.kpis,g=DATA.goals;const text=`Relatório Collin Professional 5.2\n\nClientes: ${k.clientes}\nAtivos: ${k.ativos}\nInativos/quitados: ${k.inativos}\n\nCarteira: ${money(k.carteira)}\nDevedor: ${money(k.devedor)}\nRecebido semana: ${money(k.recebidoSemana)}\n\nComissão semana: ${money(k.comissaoSemana)}\nRegra: 15% das parcelas pagas + ${money(g.ajudaCusto)} ajuda custo\nTotal 4 semanas: ${money(k.comissao4Semanas)}\nTotal + semana 5: ${money(k.comissao5Semanas)}\nProjeção mês: ${money(k.projecaoSalarioMes)}\n\nCobrança: ${k.atrasados} não pagos / ${k.cobrar} cobrar próxima semana\nVisitas: ${k.visitasCarteiraBaixa} clientes com carteira abaixo de R$150`; $('reportText').textContent=text;$('reportWhats').href='https://wa.me/?text='+encodeURIComponent(text)}
function copyReport(){copyText($('reportText').textContent)}
function renderAll(){renderKpis();renderSmart();renderClientes();renderBairros();renderCobranca();renderVisitas();renderMetas();renderComissao();renderPerformance();renderReport();drawAll();$('footerUpdate').textContent='Atualizado em '+new Date(DATA.updatedAt).toLocaleString('pt-BR');$('syncText').textContent='Base segura: '+DATA.clientes.length+' clientes'}
function drawAll(){if(!DATA)return;drawPie('statusChart',DATA.statusCounts);drawBar('bairroChart',DATA.bairros.slice(0,10).map(b=>b.bairro),DATA.bairros.slice(0,10).map(b=>b.vendas),true,true);drawBar('clientesMetaChart',['Atual','Meta'],[DATA.goals.clientesAbertos,DATA.goals.clientesMeta],false,false);drawBar('recebimentoChart',['Recebido','Meta Sem.','Meta Mês'],[DATA.kpis.recebidoSemana,DATA.goals.recebimentoMetaSemanal,DATA.goals.recebimentoMetaMensal],false,true);drawBar('comissaoChart',DATA.salaryWeeks.map(w=>w.semana),DATA.salaryWeeks.map(w=>w.comissao),false,true);drawBar('salarioChart',['Atual','Meta'],[DATA.kpis.comissao5Semanas,DATA.goals.salarioMetaMensal],false,true);drawBar('performanceWeeklyChart',DATA.salaryWeeks.map(w=>w.semana),DATA.salaryWeeks.map(w=>w.comissao),false,true);drawBar('projectionChart',['Atual','Projeção','Meta'],[DATA.kpis.comissao5Semanas,DATA.kpis.projecaoSalarioMes,DATA.goals.salarioMetaMensal],false,true)}
function drawPie(id,obj){const c=$(id);if(!c)return;const ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||400,h=Number(c.getAttribute('height')||260);c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const vals=Object.values(obj),total=vals.reduce((a,b)=>a+b,0)||1,colors=['#C89080','#10B981','#F59E0B','#EF4444','#2563EB'];let start=-Math.PI/2,cx=w/2,cy=h/2,r=Math.min(w,h)*.34;vals.forEach((v,i)=>{const a=v/total*Math.PI*2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,start,start+a);ctx.fillStyle=colors[i%colors.length];ctx.fill();start+=a});ctx.fillStyle='#111827';ctx.font='900 28px Arial';ctx.textAlign='center';ctx.fillText(total,cx,cy+6)}
function drawBar(id,labels,values,horizontal=false,moneyFormat=false){const c=$(id);if(!c)return;const ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||600,h=Number(c.getAttribute('height')||300);c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const max=Math.max(...values,1);if(horizontal){const row=h/labels.length;labels.forEach((l,i)=>{const y=i*row+10,x=145,bw=(w-x-85)*(values[i]/max);ctx.fillStyle='#111827';ctx.font='bold 12px Arial';ctx.textAlign='left';ctx.fillText(String(l).slice(0,18),10,y+13);ctx.fillStyle='#eadfdb';ctx.fillRect(x,y,w-x-95,14);ctx.fillStyle='#C89080';ctx.fillRect(x,y,bw,14);ctx.fillStyle='#777';ctx.fillText(moneyFormat?compact(values[i]):values[i],w-80,y+13)})}else{const pad=38,step=(w-pad*2)/values.length,bw=step*.55;values.forEach((v,i)=>{const bh=(h-pad*2)*(v/max),x=pad+i*step+(step-bw)/2,y=h-pad-bh;ctx.fillStyle='#C89080';ctx.fillRect(x,y,bw,bh);ctx.fillStyle='#111827';ctx.font='bold 11px Arial';ctx.textAlign='center';ctx.fillText(moneyFormat?compact(v):v,x+bw/2,y-7);ctx.fillStyle='#777';ctx.fillText(labels[i],x+bw/2,h-12)})}}
function compact(v){return v>=1000?'R$ '+(v/1000).toFixed(1)+'k':money(v)}
document.querySelectorAll('#nav button').forEach(btn=>btn.onclick=()=>tab(btn.dataset.tab));
$('searchInput').oninput=renderClientes;
$('syncBtn').onclick=loadData;
window.addEventListener('resize',()=>setTimeout(drawAll,100));
loadData();
